=== Imtenan/KTAB/examples/reformpri/doc/reformpri.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Scenario">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="desc"/>
        <xs:element ref="Items"/>
        <xs:element ref="Categories"/>
        <xs:element ref="govCost"/>
        <xs:element ref="govBudget"/>
        <xs:element ref="outOfBudgetFactor"/>
        <xs:element ref="orderFactor"/>
        <xs:element ref="Actor" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="name">
    <xs:complexType>
      <xs:attribute name="string" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="desc">
    <xs:complexType>
      <xs:attribute name="string" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Items">
    <xs:complexType>
      <xs:attribute name="listOfStrings" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Categories">
    <xs:complexType>
      <xs:attribute name="listOfStrings" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="govCost">
    <xs:complexType>
      <xs:attribute name="listOfIntegers" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="govBudget">
    <xs:complexType>
      <xs:attribute name="integer" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="outOfBudgetFactor">
    <xs:complexType>
      <xs:attribute name="float" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="orderFactor">
    <xs:complexType>
      <xs:attribute name="float" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Actor">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="description"/>
        <xs:element ref="capability"/>
        <xs:element ref="itemValues"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="description">
    <xs:complexType>
      <xs:attribute name="string" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="capability">
    <xs:complexType>
      <xs:attribute name="float" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="itemValues">
    <xs:complexType>
      <xs:attribute name="listOfIntegers" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Imtenan/KTAB/examples/reformpri/doc/reformpri-ex01.xml
<?xml version="1.0" encoding="UTF-8"  ?>

<!--
     Copyright (c) 2016, Copyright KAPSARC. Open Source MIT License.
     All rights reserved. This program and the accompanying materials
     are made available under the terms of the MIT Public License v1.0
     which accompanies this distribution, and is available at
     https://opensource.org/licenses/MIT
    
     Contributors:
         KAPSARC - initial API and implementation
 -->
<Scenario 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="reformpri.xsd"> 
<name string="RP-Scen-00"/>
<desc string="A very simple scenario"/>
<Items  listOfStrings="Edu Def Fin Jst" />
<Categories listOfStrings="First Second Third" />
  <govCost listOfIntegers='32 41 27 45'/>
   <govBudget integer="100" />
  <obFactor float="0.10"/>

    <Actor>
    <name string="Alice" />
    <description string="One of the RP actors" />
    <capability float="72.2" />
    <itemValues listOfIntegers='65 60 40 40'/>
    </Actor>
  
    <Actor>
    <name string="Bob" />
    <description string="One of the RP actors" />
    <capability float="84.2" />
    <itemValues listOfIntegers='76 22 32 81'/>
    </Actor>
    
  
    <Actor>
    <name string="Carol" />
    <description string="One of the RP actors" />
    <capability float="73.7" />
    <itemValues listOfIntegers='21  55  92  46'/>
    </Actor>

</Scenario>
